# Generated by Django 4.0.4 on 2022-07-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sut.Nr.')),
                ('date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sut.data')),
                ('contractor', models.CharField(default='UAB E', max_length=150, verbose_name='Rangovas')),
                ('sum_obj', models.FloatField(blank=True, null=True, verbose_name='Sut.vertė')),
                ('start_date', models.DateField(null=True, verbose_name='Pradžios data')),
                ('end_date', models.DateField(null=True, verbose_name='Pabaigos data')),
                ('ex_end_date', models.DateField(null=True, verbose_name='Pratęsta iki')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kita info')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Užsakovas')),
                ('object_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.constrproject', verbose_name='Objektas')),
            ],
            options={
                'verbose_name': 'Sutartys',
                'verbose_name_plural': 'Sutartys',
            },
        ),
    ]
