# Generated by Django 4.0.4 on 2022-09-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('customer', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nr.')),
                ('date', models.DateField(verbose_name='Laikotarpis')),
                ('contractor', models.CharField(default='UAB E', max_length=100, verbose_name='Rangovas')),
                ('contract_price', models.FloatField(verbose_name='Sutarties vertė')),
                ('sum_from_begining', models.FloatField(verbose_name='Atlikta nuo pradžios')),
                ('sum_before_month', models.FloatField(verbose_name='Atlikta be ataskaitinio')),
                ('sum_p_month', models.FloatField(verbose_name='Atlikta per mėn.')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contracts', verbose_name='Sutartis')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Užsakovas')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.constrproject', verbose_name='Objektas')),
            ],
            options={
                'verbose_name': 'Forma 3',
                'verbose_name_plural': 'Forma 3',
            },
        ),
    ]
