# Generated by Django 4.0.4 on 2022-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(max_length=20, unique=True)),
                ('vat_code', models.IntegerField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('bank_code', models.CharField(max_length=20, null=True)),
                ('invoice_number', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
