# Generated by Django 4.0.4 on 2022-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_code_alter_customer_vat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank_code',
            field=models.CharField(max_length=20),
        ),
    ]
