# Generated by Django 4.0.4 on 2022-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_bank_code_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresss', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('works_part', models.CharField(choices=[('E', 'Electrical'), ('SST', 'Low current networks'), ('PVA', 'Automatisation')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
