# Generated by Django 4.0.4 on 2022-04-20 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_constproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='constproject',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AddField(
            model_name='constproject',
            name='obj_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
