# Generated by Django 4.0.4 on 2022-07-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstrProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=200, verbose_name='Objekto pavadinimas')),
                ('address', models.CharField(max_length=200, verbose_name='Adresas')),
                ('start_date', models.DateField(verbose_name='Pradžia')),
                ('end_date', models.DateField(verbose_name='Pabaiga')),
                ('works_part', models.CharField(choices=[('E', 'Electrical'), ('SST', 'Low current networks'), ('PVA', 'Automatisation'), ('Oth', 'Other')], max_length=20, verbose_name='Darbai')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer', verbose_name='Užsakovas')),
            ],
            options={
                'verbose_name': 'Objektai',
                'verbose_name_plural': 'Objektai',
            },
        ),
    ]
